"""added quantity in purchase table

Revision ID: aee8e36a09a6
Revises: db69c5b7f5b7
Create Date: 2025-05-10 15:43:06.273260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee8e36a09a6'
down_revision: Union[str, None] = 'db69c5b7f5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('quantity', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('purchases', 'quantity', existing_type=sa.Integer(), nullable=False, server_default='1')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'quantity')
    # ### end Alembic commands ###
