"""changes to product table

Revision ID: bda5589fa4ae
Revises: e0d40fe53395
Create Date: 2025-05-07 10:55:16.741762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda5589fa4ae'
down_revision: Union[str, None] = 'e0d40fe53395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('final_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('discount', sa.String(), nullable=True))
    op.add_column('products', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('rating_stars', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sizes', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('colors', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('seller', sa.String(), nullable=True))
    op.add_column('products', sa.Column('top_reviews', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('categories', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'timestamp')
    op.drop_column('products', 'categories')
    op.drop_column('products', 'top_reviews')
    op.drop_column('products', 'seller')
    op.drop_column('products', 'colors')
    op.drop_column('products', 'sizes')
    op.drop_column('products', 'rating_stars')
    op.drop_column('products', 'image_urls')
    op.drop_column('products', 'currency')
    op.drop_column('products', 'discount')
    op.drop_column('products', 'final_price')
    # ### end Alembic commands ###
